"""empty message

Revision ID: 5be3d051e463
Revises: 2e73fb71074d
Create Date: 2024-04-16 09:31:54.903684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be3d051e463'
down_revision = '2e73fb71074d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('rollno', sa.String(length=120), nullable=False),
    sa.Column('division', sa.String(length=80), nullable=False),
    sa.Column('branch', sa.String(length=80), nullable=False),
    sa.Column('regid', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch'),
    sa.UniqueConstraint('division'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('regid'),
    sa.UniqueConstraint('rollno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_data')
    # ### end Alembic commands ###
