"""empty message

Revision ID: 7e016fef633c
Revises: 5be3d051e463
Create Date: 2024-04-16 09:33:44.902415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e016fef633c'
down_revision = '5be3d051e463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_data', schema=None) as batch_op:
        batch_op.drop_index('branch')
        batch_op.drop_index('division')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_data', schema=None) as batch_op:
        batch_op.create_index('division', ['division'], unique=True)
        batch_op.create_index('branch', ['branch'], unique=True)

    # ### end Alembic commands ###
